services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    command: run -c /etc/v2ray/config.json
    volumes:
      - ./config.json:/etc/v2ray/config.json:ro
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true 